name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.*'
          distribution: 'temurin'
      - name: Grant execute premission for gradle
        run: chmod +x gradlew
      - name: Run Tests
        run: ./gradlew test

  build:
    needs: tests
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.*'
          distribution: 'temurin'
      - name: Grant execute premission for gradle
        run: chmod +x gradlew
      - name: Build with Gradl
        run: ./gradlew build
      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v6.1
        with:
          image: trymstenberg/docker-java-app-ga-version
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}